/rm_decision_node:
  ros__parameters:
    home_pose: [ 0.0, 0.0, 0.0 ]

    strategy: 2

    Guard_points: [ -0.5, 1.6, 0.0,
              -0.5, 2.4, 0.0,
              -1.0, 2.4, 0.0 ]
    self_addhp_point: [ 0.0, 0.0, 0.0 ]
    self_base_point: [ 0.0, 0.0, 0.0 ]

    S1_Stop_Engineer_point: [ 0.0, 0.0, 0.0 ]
    S1_Stop_Hero_point: [ 0.0, 0.0, 0.0 ]
    S1_Outpost_point: [ 0.0, 0.0, 0.0 ]

    S2_Outpose_point: [ 0.0, 0.0, 0.0 ]

    S3_Patro_points: [ 0.0, 0.0, 0.0,
                          1.0, 2.0, 0.0]

    #will be used if shangpo is not available
    Guard_points2: [0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0]